// Vendors the display and interface faces the stage sets, so the window on
// Windows and the export on WSL render the same type: latin subsets of the
// variable weights, pulled from Google Fonts once and committed under
// renderer/assets/fonts with renderer/fonts.css generated beside them.
//
//   node scripts/vendor-fonts.mjs
//
// Segoe UI Variable stays the app's own interface face (styles.css); the
// film never depends on a font the render machine may not have.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(REPO_ROOT, "renderer", "assets", "fonts");
const CSS = path.join(REPO_ROOT, "renderer", "fonts.css");
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36";
const FAMILIES = [
  "Inter:wght@400..900",
  "Space+Grotesk:wght@400..700",
  "Fraunces:opsz,wght@9..144,400..900",
  "Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900",
  "Archivo:wght@400..900",            // grotesque with a wide weight range: broadcast
  "Playfair+Display:wght@400..900",   // high-contrast serif: editorial titles
  "DM+Sans:opsz,wght@9..40,400..900", // friendly geometric: explainers
  "JetBrains+Mono:wght@400..800",     // the mono face: terminal looks, code, figures
];

fs.mkdirSync(OUT, { recursive: true });
const faces = [];
for (const spec of FAMILIES) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, { headers: { "User-Agent": UA } })).text();
  for (const [, subset, body] of css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)) {
    if (subset !== "latin") continue;
    const family = /font-family:\s*'([^']+)'/.exec(body)[1];
    const style = /font-style:\s*(\w+)/.exec(body)[1];
    const weight = /font-weight:\s*([\d ]+)/.exec(body)[1].trim();
    const url = /url\((https:[^)]+)\)/.exec(body)[1];
    const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${style}`;
    const file = path.join(OUT, `${slug}.woff2`);
    if (!fs.existsSync(file)) fs.writeFileSync(file, Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer()));
    faces.push({ family, style, weight, slug, bytes: fs.statSync(file).size });
  }
}
const lines = [
  "/* Vendored display and interface faces (Google Fonts, latin subsets, variable",
  "   weight), so the window on Windows and the export on WSL set the same",
  "   type. Generated by scripts/vendor-fonts.mjs; edit that, not this. */",
  "",
];
for (const face of faces) {
  lines.push("@font-face {", `  font-family: "${face.family}";`, `  font-style: ${face.style};`, `  font-weight: ${face.weight};`, `  src: url("assets/fonts/${face.slug}.woff2") format("woff2");`, "}", "");
}
fs.writeFileSync(CSS, lines.join("\n"));
for (const face of faces) console.log(`${face.family} ${face.style} ${face.weight}: ${(face.bytes / 1024).toFixed(0)} KB`);
console.log(`wrote ${path.relative(REPO_ROOT, CSS)}`);
